FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
WORKDIR /
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-sac2016 AS build
WORKDIR /
COPY *.sln ./
COPY NetCoreDockerWebApp/NetCoreDockerWebApp.csproj NetCoreDockerWebApp/
RUN dotnet restore
COPY . .
WORKDIR /NetCoreDockerWebApp
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "NetCoreDockerWebApp.dll"]
